[package]
name = "jh7110-vf2-12a-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.1.2", optional = true }
riscv = "0.10.1"
riscv-rt = { version = "0.11.0", optional = true }
vcell = "0.1.3"

[features]
rt = ["riscv-rt"]
